In [1]:
print = 'hello world'

In [3]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 2.2 MB/s eta 0:00:05
   ---- ----------------------------------- 1.0/9.8 MB 2.2 MB/s eta 0:00:04
   ------- -------------------------------- 1.8/9.8 MB 2.3 MB/s eta 0:00:04
   -------- ------------------------------- 2.1/9.8 MB 2.2 MB/s eta 0:00:04
   --------- ------------------------------ 2.4/9.8 MB 2.2 MB/s eta 0:00:04
   ----------- ---------------------------- 2.9/9.8 MB 2.0 MB/s eta 0:00:04
   ------------ --------------------------- 3.1/9.8 MB 2.0 MB/s eta 0:00:04
   --------------- ------------------------ 3.7/9.8 MB 1.9 MB/s eta 0:00:04
   ---------------- ----------------------- 3.9/9.8 MB 1.9 MB/s eta 0:00:04
   ------------------ --------------------- 4.5/9.8 MB 1.9 MB/s eta 0:00:03
   ------------------- -------------------- 4.7/9.8 MB 1.9 MB/s eta 0:00:03
   -------------------- ------------------- 5.0/9.8 MB 1.8 MB/s eta 0:00:03
   --------------------- ------------------ 5.2/9.8 MB 1.8 MB/s eta 0:00:03
   ----------------------- ---------------- 5.8/9.8 MB 1.8 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.8 MB 1.8 MB/s eta 0:00:03
   -------------------------- ------------- 6.6/9.8 MB 1.8 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.8 MB 1.8 MB/s eta 0:00:02
   ------------------------------ --------- 7.3/9.8 MB 1.8 MB/s eta 0:00:02
   ------------------------------- -------- 7.6/9.8 MB 1.8 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.8 MB 1.8 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.8 MB 1.8 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.8 MB 1.8 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.8 MB 1.8 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 1.8 MB/s  0:00:05
Installing collected packages: pandas
Successfully installed pandas-3.0.3
Note: you may need to restart the kernel to use updated packages.

In [1]:
import importlib
import os

importlib.reload(os)

print(os.getcwd())

c:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code

In [4]:
import pandas as pd

df = pd.read_csv("C:/Users/ASUS/Downloads/directory.csv")

In [7]:
df.tail(50)

,Brand,Store Number,Store Name,Ownership Type,Street Address,City,State/Province,Country,Postcode,Phone Number,Timezone,Longitude,Latitude
25550,Starbucks,9619-97642,Eastridge Mall- Casper,Company Owned,4585 East 2nd St.,Casper,WY,US,826094317,307-234-9470,GMT-07:00 America/Denver,-106.26,42.85
25551,Starbucks,79668-108627,Ridley's Casper #1132,Licensed,300 E Wyoming Blvd,Casper,WY,US,826094201,NaN,GMT-07:00 America/Denver,-106.27,42.85
25552,Starbucks,11862-103659,Cy Ave & SW Wyoming Blvd - Casper,Company Owned,4003 Cy Ave,Casper,WY,US,826044238,307-234-6550,GMT-07:00 America/Denver,-106.37,42.82
25553,Starbucks,28265-237406,King Soopers-Cheyenne #79,Licensed,3702 Dell Range Blvd,Cheyenne,WY,US,82009,307-638-0014,GMT-07:00 America/Denver,-104.76,41.16
25554,Starbucks,74427-94041,Safeway-Cheyenne #2667,Licensed,700 S Greeley Hwy,Cheyenne,WY,US,820072848,307-635-7877,GMT-07:00 America/Denver,-104.80,41.11
25555,Starbucks,73370-24376,Albertsons - Cheyenne #0065,Licensed,3355 E. Pershing Blvd.,Cheyenne,WY,US,820015764,307-635-1151,GMT-07:00 America/Denver,-104.77,41.14
25556,Starbucks,73277-27188,Albertsons - Cheyenne #0066,Licensed,5800 Yellowstone Rd.,Cheyenne,WY,US,820094131,307-637-8171,GMT-07:00 America/Denver,-104.83,41.17
25557,Starbucks,29314-251304,Yellowstone and Storey - Cheyenne,Company Owned,5930Yellowstone Rd,Cheyenne,WY,US,82009,3073317443,GMT-07:00 America/Denver,-104.83,41.17
25558,Starbucks,11082-102939,"21st & Central Avenue-Cheyenne, WY",Company Owned,"2111 Central Ave, Dell Range Marketplace",Cheyenne,WY,US,820013744,307-632-2430,GMT-07:00 America/Denver,-104.82,41.14
25559,Starbucks,6515-63127,Dell Range Marketplace,Company Owned,"3610 Dell Range Boulevard, Unit A6",Cheyenne,WY,US,820095448,307-634-3433,GMT-07:00 America/Denver,-104.77,41.16
25560,Starbucks,17716-126790,Albertsons-Cody #2061,Licensed,1825 17th St,Cody,WY,US,824144701,307-527-7007,GMT-07:00 America/Denver,-109.05,44.52
25561,Starbucks,73334-24378,Albertsons - Gillette #0067,Licensed,2610 S. Douglas Hwy.,Gillette,WY,US,827186468,307-686-7352,GMT-07:00 America/Denver,-105.49,44.27
25562,Starbucks,11320-103719,I-90 & S Douglas Hwy - Gillette,Company Owned,1215 S Douglas Hwy,Gillette,WY,US,827164981,307-682-3751,GMT-07:00 America/Denver,-105.49,44.28
25563,Starbucks,19240-195904,"Jackson, WY",Company Owned,10 East Broadway,Jackson,WY,US,83001,3077344471,GMT-07:00 America/Denver,-110.76,43.48
25564,Starbucks,16502-171825,Albertsons-Jackson Hole #183,Licensed,105 Buffalo Way,Jackson,WY,US,830014806,307-733-5950,GMT-07:00 America/Denver,-110.79,43.47
25565,Starbucks,18274-101208,Smith's - Jackson Hole #184,Licensed,South Hwy 89 High School Rd,Jackson Hole,WY,US,83001,307-733-8908,GMT-07:00 America/Denver,-110.75,43.48
25566,Starbucks,22353-220004,Safeway - Lander 2761,Licensed,1165 Main St.,Lander,WY,US,82520,307-332-3636,GMT-07:00 America/Denver,-108.75,42.84
25567,Starbucks,74385-87621,Safeway-Laramie #2466,Licensed,554 N 3rd St,Laramie,WY,US,820723012,307-721-5107,GMT-07:00 America/Denver,-105.59,41.32
25568,Starbucks,73320-24375,Ridley's - Laramie #1131,Licensed,3112 E. Grand,Laramie,WY,US,820705141,307-742-8146,GMT-07:00 America/Denver,-105.56,41.31
25569,Starbucks,22425-219024,Laramie - Grand & 30th,Company Owned,3021 Grand Ave,Laramie,WY,US,82070,307-742-3262,GMT-07:00 America/Denver,-105.56,41.31
25570,Starbucks,10849-103163,I-80 & Dewar Dr-Rock Springs,Company Owned,118 Westland Way,Rock Springs,WY,US,829015751,307-362-7145,GMT-07:00 America/Denver,-109.25,41.58
25571,Starbucks,10769-102454,Coffeen & Brundage Lane-Sheridan,Company Owned,2208 Coffeen Ave,Sheridian,WY,US,828016213,307-672-5129,GMT-07:00 America/Denver,-106.94,44.77
25572,Starbucks,48482-263452,Phạm Ngọc Thạch,Licensed,"2 Phạm Ngọc Thạch, Quận Đống Đa",Hà Nội,HN,VN,0,04 3637 4374,GMT+000000 Asia/Saigon,105.83,21.01
25573,Starbucks,24015-232287,Press Club,Licensed,"59A Lý Thái Tổ, Quận Hoàn Kiếm, #123 Tầng trệt...",Hà Nội,HN,VN,70000,04 3936 9017,GMT+000000 Asia/Saigon,105.86,21.03
25574,Starbucks,24016-230012,IPH,Licensed,"241 Xuân Thủy, Quận Cầu Giấy",Hà Nội,HN,VN,70000,04 3795 4278,GMT+000000 Asia/Saigon,105.78,21.04
25575,Starbucks,47910-260386,The Garden,Licensed,"Tầng 1, TTTM The Garden, khu đô thị The Manor,...",Hà Nội,HN,VN,70000,04 3395 3333,GMT+000000 Asia/Saigon,105.78,21.01
25576,Starbucks,24003-228944,Lan Viên,Licensed,"32 Hàng Bài, Quận Hoàn Kiếm",Hà Nội,HN,VN,70000,04 3936 8407,GMT+000000 Asia/Saigon,105.85,21.02
25577,Starbucks,24014-231244,Bà Triệu,Licensed,"314 Bà Triệu, Quận Hai Bà Trưng",Hà Nội,HN,VN,70000,04 3978 1817,GMT+000000 Asia/Saigon,105.85,21.01
25578,Starbucks,49436-269127,The Vista,Licensed,"628 Xa Lo Ha Noi Highway, Dist 2, Ground Floor...",Ho Chi Minh,SG,VN,70000,08 6281 4546,GMT+000000 Asia/Saigon,106.75,10.80
25579,Starbucks,49441-269128,Ibis building,Licensed,"2 Hong Ha st, Ward 2, Tan Binh Dist, Tầng trệt...",Ho Chi Minh,SG,VN,0,NaN,GMT+000000 Asia/Saigon,106.67,10.81
25580,Starbucks,18663-190626,President Place,Licensed,"93 Nguyễn Du, Quận 1, Tầng trệt Trung Tâm Thươ...",Thành Phố Hồ Chí Minh,SG,VN,70000,08 3822 5891,GMT+000000 Asia/Saigon,106.70,10.78
25581,Starbucks,24011-230014,Pandora,Licensed,"1/1 Trường Chinh, Quận Tân Phú",Thành Phố Hồ Chí Minh,SG,VN,70000,08 3812 6830,GMT+000000 Asia/Saigon,106.63,10.81
25582,Starbucks,23633-223885,Đông Du,Licensed,"38 Đông Du, Quận 1",Thành Phố Hồ Chí Minh,SG,VN,70000,NaN,GMT+000000 Asia/Saigon,106.70,10.78
25583,Starbucks,23925-226964,Đề Thám,Licensed,"191 - 193 Đề Thám, Quận 1",Thành Phố Hồ Chí Minh,SG,VN,70000,08 3838 6455,GMT+000000 Asia/Saigon,106.69,10.77
25584,Starbucks,48282-262438,Nguyễn Văn Trỗi,Licensed,"66 Nguyễn Văn Trỗi, Quận Phú Nhuận, Tầng trệt,...",Thành Phố Hồ Chí Minh,SG,VN,0,08 3842 2171,GMT+000000 Asia/Saigon,106.68,10.79
25585,Starbucks,25378-234124,VivoCity,Licensed,"1058 Nguyễn Văn Linh, Quận 7",Thành Phố Hồ Chí Minh,SG,VN,70000,08 3771 4975,GMT+000000 Asia/Saigon,106.70,10.73
25586,Starbucks,29695-254869,Lakai,Licensed,"98-126 Nguyễn Tri Phương, Quận 5",Thành Phố Hồ Chí Minh,SG,VN,70000,08 3924 1251,GMT+000000 Asia/Saigon,106.67,10.75
25587,Starbucks,48731-264926,Thành Phố Hồ Chí Minh,Licensed,"Sân bay Tân Sơn Nhất, 45 Trường Sơn, Tân Bì...",Thành Phố Hồ Chí Minh,SG,VN,70000,08 6681 6463,GMT+000000 Asia/Saigon,106.66,10.81
25588,Starbucks,25865-242710,Kumho,Licensed,"39 Lê Duẩn, Quận 1",Thành Phố Hồ Chí Minh,SG,VN,70000,08 3823 4990,GMT+000000 Asia/Saigon,106.70,10.78
25589,Starbucks,24009-223886,Phan Xich Long,Licensed,"214 -216 Phan Xích Long, Quận Phú Nhuận",Thành Phố Hồ Chí Minh,SG,VN,70000,08 3517 6461,GMT+000000 Asia/Saigon,106.69,10.80
25590,Starbucks,25346-240592,Thảo Điền,Licensed,"21 Thảo Điền, Quận 2",Thành Phố Hồ Chí Minh,SG,VN,70000,08 3744 2040,GMT+000000 Asia/Saigon,106.74,10.80
25591,Starbucks,29047-252265,Nguyễn Huệ,Licensed,"99 Nguyễn Huệ, Quận 1",Thành Phố Hồ Chí Minh,SG,VN,70000,08 3821 0105,GMT+000000 Asia/Saigon,106.70,10.77
25592,Starbucks,27767-248666,SSG,Licensed,"561A Điện Biên Phủ, Quận Bình Thạnh, Khách sạn...",Thành Phố Hồ Chí Minh,SG,VN,70000,08 3512 0585,GMT+000000 Asia/Saigon,106.72,10.80
25593,Starbucks,18687-193924,New World,Licensed,"76 Lê Lai, Quận 1, Góc đường Phạm Hồng Thái và...",Thành Phố Hồ Chí Minh,SG,VN,70000,08 3823 7952,GMT+000000 Asia/Saigon,106.69,10.77
25594,Starbucks,27082-246744,Emart,Licensed,"168 Phan Văn Trị, Quận Gò Vấp, Khách sạn Rex",Thành Phố Hồ Chí Minh,SG,VN,70000,08 3588 0146,GMT+000000 Asia/Saigon,106.69,10.82
25595,Starbucks,21401-212072,Rex,Licensed,"141 Nguyễn Huệ, Quận 1, Góc đường Pasteur và L...",Thành Phố Hồ Chí Minh,SG,VN,70000,08 3824 4668,GMT+000000 Asia/Saigon,106.70,10.78
25596,Starbucks,24010-226985,Panorama,Licensed,"SN-44, Tòa Nhà Panorama, 208 Trần Văn Trà, Quận 7",Thành Phố Hồ Chí Minh,SG,VN,70000,08 5413 8292,GMT+000000 Asia/Saigon,106.71,10.72
25597,Starbucks,47608-253804,Rosebank Mall,Licensed,"Cnr Tyrwhitt and Cradock Avenue, Rosebank",Johannesburg,GT,ZA,2194,27873500159,GMT+000000 Africa/Johannesburg,28.04,-26.15
25598,Starbucks,47640-253809,Menlyn Maine,Licensed,"Shop 61B, Central Square, Cnr Aramist & Coroba...",Menlyn,GT,ZA,181,NaN,GMT+000000 Africa/Johannesburg,28.28,-25.79
25599,Starbucks,47609-253286,Mall of Africa,Licensed,"Shop 2077, Upper Level, Waterfall City",Midrand,GT,ZA,1682,27873500215,GMT+000000 Africa/Johannesburg,28.11,-26.02

In [8]:
df.info

<bound method DataFrame.info of            Brand  Store Number        Store Name Ownership Type  \
0      Starbucks  47370-257954     Meritxell, 96       Licensed
1      Starbucks  22331-212325  Ajman Drive Thru       Licensed
2      Starbucks  47089-256771         Dana Mall       Licensed
3      Starbucks  22126-218024        Twofour 54       Licensed
4      Starbucks  17127-178586      Al Ain Tower       Licensed
...          ...           ...               ...            ...
25595  Starbucks  21401-212072               Rex       Licensed
25596  Starbucks  24010-226985          Panorama       Licensed
25597  Starbucks  47608-253804     Rosebank Mall       Licensed
25598  Starbucks  47640-253809      Menlyn Maine       Licensed
25599  Starbucks  47609-253286    Mall of Africa       Licensed

                                          Street Address  \
0                                      Av. Meritxell, 96
1                                   1 Street 69, Al Jarf
2                           Sheikh Khalifa Bin Zayed St.
3                                        Al Salam Street
4                        Khaldiya Area, Abu Dhabi Island
...                                                  ...
25595  141 Nguyễn Huệ, Quận 1, Góc đường Pasteur và L...
25596  SN-44, Tòa Nhà Panorama, 208 Trần Văn Trà, Quận 7
25597          Cnr Tyrwhitt and Cradock Avenue, Rosebank
25598  Shop 61B, Central Square, Cnr Aramist & Coroba...
25599             Shop 2077, Upper Level, Waterfall City

                        City State/Province Country Postcode  Phone Number  \
0           Andorra la Vella              7      AD    AD500     376818720
1                      Ajman             AJ      AE      NaN           NaN
2                      Ajman             AJ      AE      NaN           NaN
3                  Abu Dhabi             AZ      AE      NaN           NaN
4                  Abu Dhabi             AZ      AE      NaN           NaN
...                      ...            ...     ...      ...           ...
25595  Thành Phố Hồ Chí Minh             SG      VN    70000  08 3824 4668
25596  Thành Phố Hồ Chí Minh             SG      VN    70000  08 5413 8292
25597           Johannesburg             GT      ZA     2194   27873500159
25598                 Menlyn             GT      ZA      181           NaN
25599                Midrand             GT      ZA     1682   27873500215

                             Timezone  Longitude  Latitude
0             GMT+1:00 Europe/Andorra       1.53     42.51
1                GMT+04:00 Asia/Dubai      55.47     25.42
2                GMT+04:00 Asia/Dubai      55.47     25.39
3                GMT+04:00 Asia/Dubai      54.38     24.48
4                GMT+04:00 Asia/Dubai      54.54     24.51
...                               ...        ...       ...
25595          GMT+000000 Asia/Saigon     106.70     10.78
25596          GMT+000000 Asia/Saigon     106.71     10.72
25597  GMT+000000 Africa/Johannesburg      28.04    -26.15
25598  GMT+000000 Africa/Johannesburg      28.28    -25.79
25599  GMT+000000 Africa/Johannesburg      28.11    -26.02

[25600 rows x 13 columns]>

In [10]:
df.describe(include='all')

,Brand,Store Number,Store Name,Ownership Type,Street Address,City,State/Province,Country,Postcode,Phone Number,Timezone,Longitude,Latitude
count,25600,25600,25600,25600,25598,25585,25600,25600,24078,18739,25600,25599.000000,25599.000000
unique,4,25599,25364,4,25353,5469,338,73,18887,18498,101,NaN,NaN
top,Starbucks,19773-160973,Starbucks,Company Owned,"Circular Building #6, Guard Post 8",上海市,CA,US,0,4.20235E+11,GMT-05:00 America/New_York,NaN,NaN
freq,25249,2,224,11932,11,542,2821,13608,101,26,4889,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-27.872234,34.793016
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.844046,13.342332
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-159.460000,-46.410000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-104.665000,31.240000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-79.350000,36.750000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.630000,41.570000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176.920000,64.850000

In [11]:
df.isnull().sum()

Brand                0
Store Number         0
Store Name           0
Ownership Type       0
Street Address       2
City                15
State/Province       0
Country              0
Postcode          1522
Phone Number      6861
Timezone             0
Longitude            1
Latitude             1
dtype: int64

In [12]:
df.mean

<bound method DataFrame.mean of            Brand  Store Number        Store Name Ownership Type  \
0      Starbucks  47370-257954     Meritxell, 96       Licensed
1      Starbucks  22331-212325  Ajman Drive Thru       Licensed
2      Starbucks  47089-256771         Dana Mall       Licensed
3      Starbucks  22126-218024        Twofour 54       Licensed
4      Starbucks  17127-178586      Al Ain Tower       Licensed
...          ...           ...               ...            ...
25595  Starbucks  21401-212072               Rex       Licensed
25596  Starbucks  24010-226985          Panorama       Licensed
25597  Starbucks  47608-253804     Rosebank Mall       Licensed
25598  Starbucks  47640-253809      Menlyn Maine       Licensed
25599  Starbucks  47609-253286    Mall of Africa       Licensed

                                          Street Address  \
0                                      Av. Meritxell, 96
1                                   1 Street 69, Al Jarf
2                           Sheikh Khalifa Bin Zayed St.
3                                        Al Salam Street
4                        Khaldiya Area, Abu Dhabi Island
...                                                  ...
25595  141 Nguyễn Huệ, Quận 1, Góc đường Pasteur và L...
25596  SN-44, Tòa Nhà Panorama, 208 Trần Văn Trà, Quận 7
25597          Cnr Tyrwhitt and Cradock Avenue, Rosebank
25598  Shop 61B, Central Square, Cnr Aramist & Coroba...
25599             Shop 2077, Upper Level, Waterfall City

                        City State/Province Country Postcode  Phone Number  \
0           Andorra la Vella              7      AD    AD500     376818720
1                      Ajman             AJ      AE      NaN           NaN
2                      Ajman             AJ      AE      NaN           NaN
3                  Abu Dhabi             AZ      AE      NaN           NaN
4                  Abu Dhabi             AZ      AE      NaN           NaN
...                      ...            ...     ...      ...           ...
25595  Thành Phố Hồ Chí Minh             SG      VN    70000  08 3824 4668
25596  Thành Phố Hồ Chí Minh             SG      VN    70000  08 5413 8292
25597           Johannesburg             GT      ZA     2194   27873500159
25598                 Menlyn             GT      ZA      181           NaN
25599                Midrand             GT      ZA     1682   27873500215

                             Timezone  Longitude  Latitude
0             GMT+1:00 Europe/Andorra       1.53     42.51
1                GMT+04:00 Asia/Dubai      55.47     25.42
2                GMT+04:00 Asia/Dubai      55.47     25.39
3                GMT+04:00 Asia/Dubai      54.38     24.48
4                GMT+04:00 Asia/Dubai      54.54     24.51
...                               ...        ...       ...
25595          GMT+000000 Asia/Saigon     106.70     10.78
25596          GMT+000000 Asia/Saigon     106.71     10.72
25597  GMT+000000 Africa/Johannesburg      28.04    -26.15
25598  GMT+000000 Africa/Johannesburg      28.28    -25.79
25599  GMT+000000 Africa/Johannesburg      28.11    -26.02

[25600 rows x 13 columns]>

In [13]:
df['Store_Count'] = df.groupby('City')['Brand'].transform('count')
print(df.head())

       Brand  Store Number        Store Name Ownership Type  \
0  Starbucks  47370-257954     Meritxell, 96       Licensed
1  Starbucks  22331-212325  Ajman Drive Thru       Licensed
2  Starbucks  47089-256771         Dana Mall       Licensed
3  Starbucks  22126-218024        Twofour 54       Licensed
4  Starbucks  17127-178586      Al Ain Tower       Licensed

                    Street Address              City State/Province Country  \
0                Av. Meritxell, 96  Andorra la Vella              7      AD
1             1 Street 69, Al Jarf             Ajman             AJ      AE
2     Sheikh Khalifa Bin Zayed St.             Ajman             AJ      AE
3                  Al Salam Street         Abu Dhabi             AZ      AE
4  Khaldiya Area, Abu Dhabi Island         Abu Dhabi             AZ      AE

  Postcode Phone Number                 Timezone  Longitude  Latitude  \
0    AD500    376818720  GMT+1:00 Europe/Andorra       1.53     42.51
1      NaN          NaN     GMT+04:00 Asia/Dubai      55.47     25.42
2      NaN          NaN     GMT+04:00 Asia/Dubai      55.47     25.39
3      NaN          NaN     GMT+04:00 Asia/Dubai      54.38     24.48
4      NaN          NaN     GMT+04:00 Asia/Dubai      54.54     24.51

   Store_Count
0          1.0
1          2.0
2          2.0
3         43.0
4         43.0

In [14]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [15]:
df.columns

Index(['brand', 'store_number', 'store_name', 'ownership_type',
       'street_address', 'city', 'state/province', 'country', 'postcode',
       'phone_number', 'timezone', 'longitude', 'latitude', 'store_count'],
      dtype='str')

In [17]:
import pandas as pd

In [18]:
df =pd.read_csv("C:/Users/ASUS/Downloads/directory.csv")

In [19]:
labels = ['Low', 'Medium', 'High']

df['Latitude_Level'] = pd.qcut(
    df['Latitude'],
    q=3,
    labels=labels
)

print(df[['Latitude', 'Latitude_Level']].head())

   Latitude Latitude_Level
0     42.51           High
1     25.42            Low
2     25.39            Low
3     24.48            Low
4     24.51            Low

In [20]:
stores_by_country = df.groupby('Country').size()
print(stores_by_country)

Country
AD        1
AE      144
AR      108
AT       18
AU       22
      ...
TT        3
TW      394
US    13608
VN       25
ZA        3
Length: 73, dtype: int64

In [21]:
stores_by_city = df.groupby('City').size()
print(stores_by_city)

City
's-Hertogenbosch      1
1~2F                  1
2-3-6 Kyonancho       1
330-9501              1
438-1 Fujisawa        1
                   ...
부산                   16
서울                  136
울산                    2
인천                    9
충청남도                  1
Length: 5469, dtype: int64

In [22]:
print(df['Ownership Type'].value_counts())

Ownership Type
Company Owned    11932
Licensed          9375
Joint Venture     3976
Franchise          317
Name: count, dtype: int64

In [23]:
df[['Brand', 'Store Number']].head(10)

       Brand  Store Number
0  Starbucks  47370-257954
1  Starbucks  22331-212325
2  Starbucks  47089-256771
3  Starbucks  22126-218024
4  Starbucks  17127-178586
5  Starbucks  17688-182164
6  Starbucks  18182-182165
7  Starbucks  23359-229184
8  Starbucks   30781-99022
9  Starbucks  20423-205465

In [24]:
df[['Brand', 'Store Name', 'Street Address']].head(10)

       Brand                Store Name                   Street Address
0  Starbucks             Meritxell, 96                Av. Meritxell, 96
1  Starbucks          Ajman Drive Thru             1 Street 69, Al Jarf
2  Starbucks                 Dana Mall     Sheikh Khalifa Bin Zayed St.
3  Starbucks                Twofour 54                  Al Salam Street
4  Starbucks              Al Ain Tower  Khaldiya Area, Abu Dhabi Island
5  Starbucks  Dalma Mall, Ground Floor             Dalma Mall, Mussafah
6  Starbucks       Dalma Mall, Level 1             Dalma Mall, Mussafah
7  Starbucks        Debenhams Yas Mall                       Yas Island
8  Starbucks          Khalidiya Street                    Khalidiya St.
9  Starbucks         Eastern Mangroves   Al Salam Street, The Mangroves

In [25]:
df[['Brand', 'Store Name', 'Street Address', 'Country','Phone Number']].head(10)

,Brand,Store Name,Street Address,Country,Phone Number
0,Starbucks,"Meritxell, 96","Av. Meritxell, 96",AD,376818720
1,Starbucks,Ajman Drive Thru,"1 Street 69, Al Jarf",AE,NaN
2,Starbucks,Dana Mall,Sheikh Khalifa Bin Zayed St.,AE,NaN
3,Starbucks,Twofour 54,Al Salam Street,AE,NaN
4,Starbucks,Al Ain Tower,"Khaldiya Area, Abu Dhabi Island",AE,NaN
5,Starbucks,"Dalma Mall, Ground Floor","Dalma Mall, Mussafah",AE,NaN
6,Starbucks,"Dalma Mall, Level 1","Dalma Mall, Mussafah",AE,NaN
7,Starbucks,Debenhams Yas Mall,Yas Island,AE,NaN
8,Starbucks,Khalidiya Street,Khalidiya St.,AE,26670052
9,Starbucks,Eastern Mangroves,"Al Salam Street, The Mangroves",AE,NaN

In [2]:
import importlib
import os

importlib.reload(os)

print(os.getcwd())

c:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code

In [5]:
df.tail(100)

,Brand,Store Number,Store Name,Ownership Type,Street Address,City,State/Province,Country,Postcode,Phone Number,Timezone,Longitude,Latitude
25500,Starbucks,19808-202245,Prairie Lakes & Grand,Company Owned,2804 Prairie Lakes Drive,Sun Prairie,WI,US,53590,6088258818,GMT-06:00 America/Chicago,-89.27,43.17
25501,Starbucks,10928-103119,Silver Spring & Highway 164,Company Owned,N65 W24950 Main Street,Sussex,WI,US,53089,262 820 0473,GMT-06:00 America/Chicago,-88.24,43.14
25502,Starbucks,25706-240885,Tomah,Company Owned,224 Buan Street,Tomah,WI,US,54660,6088550736,GMT-06:00 America/Chicago,-90.51,44.02
25503,Starbucks,9807-98204,Moreland & Delafield,Company Owned,801 W Moreland Blvd,Waukesha,WI,US,531882971,262 547 1331,GMT-06:00 America/Chicago,-88.24,43.02
25504,Starbucks,29758-251827,Meijer 276 Waukesha,Licensed,801 E SUNSET DRIVE,WAUKESHA,WI,US,53189,262-547-1109,GMT-06:00 America/Chicago,-88.22,42.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25595,Starbucks,21401-212072,Rex,Licensed,"141 Nguyễn Huệ, Quận 1, Góc đường Pasteur và L...",Thành Phố Hồ Chí Minh,SG,VN,70000,08 3824 4668,GMT+000000 Asia/Saigon,106.70,10.78
25596,Starbucks,24010-226985,Panorama,Licensed,"SN-44, Tòa Nhà Panorama, 208 Trần Văn Trà, Quận 7",Thành Phố Hồ Chí Minh,SG,VN,70000,08 5413 8292,GMT+000000 Asia/Saigon,106.71,10.72
25597,Starbucks,47608-253804,Rosebank Mall,Licensed,"Cnr Tyrwhitt and Cradock Avenue, Rosebank",Johannesburg,GT,ZA,2194,27873500159,GMT+000000 Africa/Johannesburg,28.04,-26.15
25598,Starbucks,47640-253809,Menlyn Maine,Licensed,"Shop 61B, Central Square, Cnr Aramist & Coroba...",Menlyn,GT,ZA,181,NaN,GMT+000000 Africa/Johannesburg,28.28,-25.79
25599,Starbucks,47609-253286,Mall of Africa,Licensed,"Shop 2077, Upper Level, Waterfall City",Midrand,GT,ZA,1682,27873500215,GMT+000000 Africa/Johannesburg,28.11,-26.02

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25600 entries, 0 to 25599
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           25600 non-null  str
 1   Store Number    25600 non-null  str
 2   Store Name      25600 non-null  str
 3   Ownership Type  25600 non-null  str
 4   Street Address  25598 non-null  str
 5   City            25585 non-null  str
 6   State/Province  25600 non-null  str
 7   Country         25600 non-null  str
 8   Postcode        24078 non-null  str
 9   Phone Number    18739 non-null  str
 10  Timezone        25600 non-null  str
 11  Longitude       25599 non-null  float64
 12  Latitude        25599 non-null  float64
dtypes: float64(2), str(11)
memory usage: 2.5 MB

In [10]:
import sys
print(sys.executable)

c:\Users\ASUS\AppData\Local\Programs\Python\Python313\python.exe

In [12]:
%pip install pyodbc

Requirement already satisfied: pyodbc in c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages (5.3.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pyodbc

print(pyodbc.version)
print(pyodbc.drivers())

5.3.0
['SQL Server', 'ODBC Driver 17 for SQL Server', 'ODBC Driver 18 for SQL Server']

In [5]:
import pyodbc

conn = pyodbc.connect(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=.\\SQLEXPRESS;"
    "DATABASE=Directory.Data;"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)

print("Connected successfully!")

Connected successfully!

In [6]:
import pandas as pd

df = pd.read_csv(r"C:\Users\ASUS\Downloads\directory.csv")

print(df.head())
print(df.columns)

       Brand  Store Number        Store Name Ownership Type  \
0  Starbucks  47370-257954     Meritxell, 96       Licensed
1  Starbucks  22331-212325  Ajman Drive Thru       Licensed
2  Starbucks  47089-256771         Dana Mall       Licensed
3  Starbucks  22126-218024        Twofour 54       Licensed
4  Starbucks  17127-178586      Al Ain Tower       Licensed

                    Street Address              City State/Province Country  \
0                Av. Meritxell, 96  Andorra la Vella              7      AD
1             1 Street 69, Al Jarf             Ajman             AJ      AE
2     Sheikh Khalifa Bin Zayed St.             Ajman             AJ      AE
3                  Al Salam Street         Abu Dhabi             AZ      AE
4  Khaldiya Area, Abu Dhabi Island         Abu Dhabi             AZ      AE

  Postcode Phone Number                 Timezone  Longitude  Latitude
0    AD500    376818720  GMT+1:00 Europe/Andorra       1.53     42.51
1      NaN          NaN     GMT+04:00 Asia/Dubai      55.47     25.42
2      NaN          NaN     GMT+04:00 Asia/Dubai      55.47     25.39
3      NaN          NaN     GMT+04:00 Asia/Dubai      54.38     24.48
4      NaN          NaN     GMT+04:00 Asia/Dubai      54.54     24.51
Index(['Brand', 'Store Number', 'Store Name', 'Ownership Type',
       'Street Address', 'City', 'State/Province', 'Country', 'Postcode',
       'Phone Number', 'Timezone', 'Longitude', 'Latitude'],
      dtype='str')

In [8]:
%pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.51-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.3-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.51-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 505.6 kB/s eta 0:00:04
   --------- ------------------------------ 0.5/2.1 MB 505.6 kB/s eta 0:00:04
   --------- ------------------------------ 0.5/2.1 MB 505.6 kB/s eta 0:00:04
   --------- ------------------------------ 0.5/2.1 MB 505.6 kB/s eta 0:00:04
   -------------- ------------------------- 0.8/2.1 MB 380.2 kB/s eta 0:00:04
   -------------- ------------------------- 0.8/2.1 MB 380.2 kB/s eta 0:00:04
   -------------- ------------------------- 0.8/2.1 MB 380.2 kB/s eta 0:00:04
   ------------------- -------------------- 1.0/2.1 MB 409.7 kB/s eta 0:00:03
   ------------------- -------------------- 1.0/2.1 MB 409.7 kB/s eta 0:00:03
   ------------------------ --------------- 1.3/2.1 MB 438.9 kB/s eta 0:00:02
   ------------------------ --------------- 1.3/2.1 MB 438.9 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.1 MB 456.7 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.1 MB 456.7 kB/s eta 0:00:02
   ----------------------------- ---------- 1.6/2.1 MB 456.7 kB/s eta 0:00:02
   ---------------------------------- ----- 1.8/2.1 MB 465.3 kB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 465.3 kB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 472.6 kB/s  0:00:04
Downloading greenlet-3.5.3-cp313-cp313-win_amd64.whl (239 kB)
Installing collected packages: greenlet, sqlalchemy

   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   ---------------------------------------- 2/2 [sqlalchemy]

Successfully installed greenlet-3.5.3 sqlalchemy-2.0.51
Note: you may need to restart the kernel to use updated packages.

In [1]:
from sqlalchemy import create_engine

print("SQLAlchemy installed successfully!")

SQLAlchemy installed successfully!

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\ASUS\Downloads\directory.csv")

# Check the data
print(df.head())
print(df.shape)

       Brand  Store Number        Store Name Ownership Type  \
0  Starbucks  47370-257954     Meritxell, 96       Licensed
1  Starbucks  22331-212325  Ajman Drive Thru       Licensed
2  Starbucks  47089-256771         Dana Mall       Licensed
3  Starbucks  22126-218024        Twofour 54       Licensed
4  Starbucks  17127-178586      Al Ain Tower       Licensed

                    Street Address              City State/Province Country  \
0                Av. Meritxell, 96  Andorra la Vella              7      AD
1             1 Street 69, Al Jarf             Ajman             AJ      AE
2     Sheikh Khalifa Bin Zayed St.             Ajman             AJ      AE
3                  Al Salam Street         Abu Dhabi             AZ      AE
4  Khaldiya Area, Abu Dhabi Island         Abu Dhabi             AZ      AE

  Postcode Phone Number                 Timezone  Longitude  Latitude
0    AD500    376818720  GMT+1:00 Europe/Andorra       1.53     42.51
1      NaN          NaN     GMT+04:00 Asia/Dubai      55.47     25.42
2      NaN          NaN     GMT+04:00 Asia/Dubai      55.47     25.39
3      NaN          NaN     GMT+04:00 Asia/Dubai      54.38     24.48
4      NaN          NaN     GMT+04:00 Asia/Dubai      54.54     24.51
(25600, 13)

In [3]:
from sqlalchemy import create_engine
import urllib

In [4]:
from sqlalchemy import create_engine
import urllib

conn_str = (
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=.\\SQLEXPRESS;"
    "DATABASE=Directory.Data;"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)

params = urllib.parse.quote_plus(conn_str)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [5]:
df.to_sql(
    name="directory",
    con=engine,
    if_exists="replace",   # Creates or replaces the table
    index=False
)

print("✅ CSV imported successfully!")

✅ CSV imported successfully!